services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: esteban941017/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: esteban941017/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - '8080:80'

networks:
  laranet:
    driver: bridge
